package ie.jtc.model.bingjson;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/*
 * generated by https://timboudreau.com/blog/json/read
 * the json had flummoxed me and several other parsers.
 * Tim Boundreau, kudps!
 */
public final class RouteSlim {
	public final ResourceSet resourceSets[];
	public final long statusCode;

	@JsonCreator
	public RouteSlim(@JsonProperty("resourceSets") ResourceSet[] resourceSets,
			@JsonProperty("statusCode") long statusCode) {
		this.resourceSets = resourceSets;
		this.statusCode = statusCode;
	}

	public static final class ResourceSet {
		public final long estimatedTotal;
		public final Resource resources[];

		@JsonCreator
		public ResourceSet(@JsonProperty("estimatedTotal") long estimatedTotal,
				@JsonProperty("resources") Resource[] resources) {
			this.estimatedTotal = estimatedTotal;
			this.resources = resources;
		}

		public static final class Resource {
			public final String distanceUnit;
			public final String durationUnit;
			public final double travelDistance;
			public final long travelDuration;

			@JsonCreator
			public Resource(@JsonProperty("distanceUnit") String distanceUnit,
					@JsonProperty("durationUnit") String durationUnit,
					@JsonProperty("travelDistance") double travelDistance,
					@JsonProperty("travelDuration") long travelDuration) {
				this.distanceUnit = distanceUnit;
				this.durationUnit = durationUnit;
				this.travelDistance = travelDistance;
				this.travelDuration = travelDuration;

			}

		}
	}
}